"""Monitoring tools for ClickHouse.

This module provides tools for monitoring ClickHouse database performance,
health, and operational metrics. These tools can be used by AI agents to
perform database investigations and health checks.
"""

from .error_analysis import (
    get_error_stack_traces,
    get_recent_errors,
    get_text_log,
)
from .hardware_diagnostics import (
    CPUAnalysis,
    CPUAnalyzer,
    HardwareBottleneck,
    HardwareBottleneckType,
    HardwareHealthEngine,
    HardwareHealthReport,
    HardwareSeverity,
    MemoryAnalysis,
    MemoryAnalyzer,
    ThreadPoolAnalysis,
    ThreadPoolAnalyzer,
    ThreadPoolType,
)
from .insert_operations import (
    get_async_insert_stats,
    get_async_vs_sync_insert_counts,
    get_insert_written_bytes_distribution,
    get_recent_insert_queries,
)
from .parts_merges import (
    get_current_merges,
    get_merge_stats,
    get_part_log_events,
    get_partition_stats,
    get_parts_analysis,
)
from .performance_diagnostics import (
    CacheAnalysis,
    CacheAnalyzer,
    IOPerformanceAnalysis,
    IOPerformanceAnalyzer,
    PerformanceBottleneck,
    PerformanceBottleneckType,
    PerformanceDiagnosticEngine,
    PerformanceDiagnosticReport,
    PerformanceSeverity,
    QueryExecutionAnalysis,
    QueryExecutionAnalyzer,
)
from .profile_events_core import (
    ProfileEventAggregation,
    ProfileEventComparison,
    ProfileEventDefinition,
    ProfileEventsAnalyzer,
    ProfileEventsCategory,
    ProfileEventsComparator,
    ProfileEventThreshold,
    create_profile_events_summary,
    detect_profile_event_anomalies,
    format_profile_event_value,
    get_profile_events_by_category,
)
from .query_performance import (
    get_current_processes,
    get_normalized_query_stats,
    get_query_duration_stats,
    get_query_kind_breakdown,
)
from .resource_usage import (
    get_cpu_usage,
    get_memory_usage,
    get_server_sizing,
    get_uptime,
)
from .storage_cloud_diagnostics import (
    AzureStorageAnalysis,
    AzureStorageAnalyzer,
    CompressionAnalysis,
    CompressionAnalyzer,
    S3StorageAnalysis,
    S3StorageAnalyzer,
    StorageIssue,
    StorageOptimizationEngine,
    StorageOptimizationReport,
    StoragePerformanceIssue,
    StorageSeverity,
    StorageTier,
    analyze_compression_efficiency,
    diagnose_high_storage_latency,
    diagnose_storage_throttling,
    identify_storage_cost_optimizations,
)
from .system_components import (
    get_blob_storage_stats,
    get_mv_deduplicated_blocks,
    get_mv_query_stats,
    get_s3queue_stats,
    get_s3queue_with_names,
)
from .table_statistics import (
    get_largest_tables,
    get_recent_table_modifications,
    get_table_inactive_parts,
    get_table_stats,
)
from .utility import (
    create_monitoring_views,
    generate_drop_tables_script,
    get_thread_name_distributions,
    get_user_defined_functions,
    prewarm_cache_on_all_replicas,
)

__all__ = [
    "generate_drop_tables_script",
    "get_async_insert_stats",
    "get_blob_storage_stats",
    "get_cpu_usage",
    "get_current_merges",
    "get_current_processes",
    "get_error_stack_traces",
    "get_insert_written_bytes_distribution",
    "get_memory_usage",
    "get_merge_stats",
    "get_mv_query_stats",
    "get_normalized_query_stats",
    "get_part_log_events",
    "get_partition_stats",
    "get_parts_analysis",
    "get_query_duration_stats",
    "get_query_kind_breakdown",
    "get_recent_errors",
    "get_recent_insert_queries",
    "get_s3queue_stats",
    "get_server_sizing",
    "get_table_inactive_parts",
    "get_table_stats",
    "get_text_log",
    "get_uptime",
    "get_user_defined_functions",
    "get_async_vs_sync_insert_counts",
    "get_mv_deduplicated_blocks",
    "get_s3queue_with_names",
    "get_recent_table_modifications",
    "get_largest_tables",
    "prewarm_cache_on_all_replicas",
    "get_thread_name_distributions",
    "create_monitoring_views",
    # ProfileEvents core framework
    "ProfileEventsAnalyzer",
    "ProfileEventsComparator",
    "ProfileEventsCategory",
    "ProfileEventDefinition",
    "ProfileEventAggregation",
    "ProfileEventComparison",
    "ProfileEventThreshold",
    "format_profile_event_value",
    "get_profile_events_by_category",
    "detect_profile_event_anomalies",
    "create_profile_events_summary",
    # Performance diagnostics suite
    "PerformanceDiagnosticEngine",
    "QueryExecutionAnalyzer",
    "IOPerformanceAnalyzer",
    "CacheAnalyzer",
    "PerformanceBottleneckType",
    "PerformanceSeverity",
    "PerformanceBottleneck",
    "QueryExecutionAnalysis",
    "IOPerformanceAnalysis",
    "CacheAnalysis",
    "PerformanceDiagnosticReport",
    # Storage and cloud diagnostics suite
    "S3StorageAnalyzer",
    "AzureStorageAnalyzer",
    "CompressionAnalyzer",
    "StorageOptimizationEngine",
    "StoragePerformanceIssue",
    "StorageSeverity",
    "StorageTier",
    "StorageIssue",
    "S3StorageAnalysis",
    "AzureStorageAnalysis",
    "CompressionAnalysis",
    "StorageOptimizationReport",
    "diagnose_high_storage_latency",
    "diagnose_storage_throttling",
    "analyze_compression_efficiency",
    "identify_storage_cost_optimizations",
    # Hardware diagnostics suite
    "CPUAnalyzer",
    "MemoryAnalyzer",
    "ThreadPoolAnalyzer",
    "HardwareHealthEngine",
    "HardwareBottleneckType",
    "HardwareSeverity",
    "ThreadPoolType",
    "HardwareBottleneck",
    "CPUAnalysis",
    "MemoryAnalysis",
    "ThreadPoolAnalysis",
    "HardwareHealthReport",
]
