name: 🐛 Bug Report
description: Report a bug in Agent Zero
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out this form to help us understand and reproduce the issue.

        **Security Notice**: Do not include sensitive information like passwords, API keys, or personal data.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      description: Please verify you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I am using a supported version of Agent Zero
          required: true
        - label: I have verified this is not related to my ClickHouse configuration
          required: true

  - type: input
    id: version
    attributes:
      label: Agent Zero Version
      description: What version of Agent Zero are you running?
      placeholder: "v2.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Mode
      description: How is Agent Zero deployed?
      options:
        - Local development (stdio)
        - Standalone server (SSE)
        - Docker container
        - Kubernetes
        - Enterprise deployment
    validations:
      required: true

  - type: dropdown
    id: ide
    attributes:
      label: IDE/Client
      description: Which IDE or client are you using?
      options:
        - Claude Desktop
        - Claude Code
        - Cursor
        - Windsurf
        - VS Code
        - Other (specify in description)

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure Agent Zero with...
        2. Run command...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0, Windows 11]
        - Python version: [e.g., 3.11.0]
        - ClickHouse version: [e.g., 24.1.0]
        - Network setup: [e.g., local, cloud, VPN]
      render: text
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration (Sanitized)
      description: Relevant configuration (remove sensitive data)
      placeholder: |
        ```json
        {
          "deployment_mode": "standalone",
          "server": {
            "host": "0.0.0.0",
            "port": 8505
          }
        }
        ```
      render: json

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Output
      description: Include relevant logs, error messages, or stack traces
      placeholder: |
        Please include relevant logs here. Remove or redact sensitive information.
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or information
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: compliance
    attributes:
      label: Compliance and Security
      description: Please confirm the following
      options:
        - label: I have removed all sensitive information from this report
          required: true
        - label: This bug report complies with our security disclosure policy
          required: true
        - label: I consent to this information being used to improve Agent Zero
          required: true
