# Agent Zero MCP Server - Docker Compose for Enterprise Deployment
version: '3.8'

services:
  agent-zero-mcp:
    build: .
    container_name: agent-zero-mcp
    restart: unless-stopped
    ports:
      - "8505:8505"
    environment:
      # Deployment Configuration
      - MCP_DEPLOYMENT_MODE=enterprise
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8505
      - MCP_TRANSPORT=sse

      # ClickHouse Configuration (Override with your values)
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-clickhouse}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-8443}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-password}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE:-false}
      - CLICKHOUSE_VERIFY=${CLICKHOUSE_VERIFY:-false}
      - CLICKHOUSE_CONNECT_TIMEOUT=${CLICKHOUSE_CONNECT_TIMEOUT:-30}
      - CLICKHOUSE_SEND_RECEIVE_TIMEOUT=${CLICKHOUSE_SEND_RECEIVE_TIMEOUT:-300}

      # Security Configuration
      - MCP_SSL_ENABLE=${MCP_SSL_ENABLE:-false}
      - MCP_AUTH_USERNAME=${MCP_AUTH_USERNAME}
      - MCP_AUTH_PASSWORD=${MCP_AUTH_PASSWORD}
      - MCP_OAUTH_ENABLE=${MCP_OAUTH_ENABLE:-false}
      - MCP_OAUTH_CLIENT_ID=${MCP_OAUTH_CLIENT_ID}
      - MCP_OAUTH_CLIENT_SECRET=${MCP_OAUTH_CLIENT_SECRET}

      # Feature Configuration
      - MCP_ENABLE_METRICS=true
      - MCP_ENABLE_HEALTH_CHECK=true
      - MCP_RATE_LIMIT_ENABLED=true
      - MCP_RATE_LIMIT_REQUESTS=100
      - MCP_TOOL_LIMIT=100
      - MCP_RESOURCE_LIMIT=50
      - MCP_ENABLE_STRUCTURED_OUTPUT=true
    volumes:
      - ./configs:/app/configs:ro
      - ./ssl:/app/ssl:ro  # Mount SSL certificates if needed
    networks:
      - agent-zero-network
    depends_on:
      - clickhouse
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8505/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: ClickHouse database for testing/development
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: agent-zero-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-password}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-config:/etc/clickhouse-server/config.d:ro
    networks:
      - agent-zero-network

  # Optional: Nginx reverse proxy for SSL termination and load balancing
  nginx:
    image: nginx:alpine
    container_name: agent-zero-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    networks:
      - agent-zero-network
    depends_on:
      - agent-zero-mcp
    profiles:
      - with-proxy

networks:
  agent-zero-network:
    driver: bridge

volumes:
  clickhouse-data:
    driver: local
