name: Build and Publish Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_tag
        run: |
          # Determine raw tag name; for release events, GITHUB_REF_NAME may be set
          if [ -n "${GITHUB_REF_NAME:-}" ]; then
            RAW_TAG="${GITHUB_REF_NAME}"
          else
            RAW_TAG="${GITHUB_REF#refs/tags/}"
          fi
          # Strip leading 'v' if present (v1.2.3 → 1.2.3)
          TAG="${RAW_TAG#v}"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT

      - name: Set version in __init__.py
        run: |
          # Inject the Git tag version into __init__.py
          sed -i "s/^__version__ = .*/__version__ = \"${{ steps.get_tag.outputs.TAG }}\"/" agent_zero/__init__.py
          # Print version to verify
          echo "Updated version in __init__.py:"
          cat agent_zero/__init__.py | grep "__version__"

      - name: Update version in README.md
        run: |
          sed -i "s/badge\/version-[0-9]\+\.[0-9]\+\.[0-9]\+-/badge\/version-${{ steps.get_tag.outputs.TAG }}-/" README.md

      - name: Check the version
        run: |
          cat agent_zero/__init__.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with UV
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install build setuptools wheel
          # Force a metadata refresh by cleaning any cache
          rm -rf *.egg-info
          # Now install the package
          uv pip install -e .

      - name: Verify version before build
        run: |
          source .venv/bin/activate
          # This will show the version that will be used in the build
          python -c "import agent_zero; print(f'Package version: {agent_zero.__version__}')"

      - name: Build package
        run: |
          source .venv/bin/activate
          # Use --no-isolation to pick up the updated __init__.py directly
          python -m build --sdist --wheel --no-isolation
          echo "Build successful"
          ls -l dist

      - name: Verify built package version
        run: |
          # Check that the wheel filename contains the correct version
          ls dist/*-${{ steps.get_tag.outputs.TAG }}-*.whl || { echo "Wheel with correct version not found!"; exit 1; }
          # Check that the source dist filename contains the correct version
          ls dist/*-${{ steps.get_tag.outputs.TAG }}.tar.gz || { echo "Source dist with correct version not found!"; exit 1; }
          # Show package details
          pip install pkginfo
          python -c "import pkginfo; wheel = pkginfo.Wheel('dist/ch_agent_zero-${{ steps.get_tag.outputs.TAG }}-py3-none-any.whl'); print(f'Wheel metadata: name={wheel.name}, version={wheel.version}')"

      - name: Publish to PyPI
        if: matrix.python-version == '3.13'
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
